permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: seppol
  email:
  link: 
  weibo: 
  github:
  music: 
  linkedin: 

# 站点信息
title: seppol的博客
description: My personal blog
url: http://seppol.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/LAY.png
favicon: /public/img/LAY.png

# disqus 设置
disqus:
  shortname: seppol

# 主题设置，自动激活某个标签
active: 科研


# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档